"""empty message

Revision ID: d44e648d546c
Revises: 38efe0bf8acf
Create Date: 2019-03-07 18:07:54.261190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44e648d546c'
down_revision = '38efe0bf8acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('channel_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'channel_count')
    # ### end Alembic commands ###
