"""empty message

Revision ID: e17bb2bd27ed
Revises: 
Create Date: 2019-03-06 15:49:00.504730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17bb2bd27ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=50), nullable=False),
    sa.Column('channel1', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('last_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('hardware', sa.String(length=50), nullable=False),
    sa.Column('software', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('vasid', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('last_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vasid'], ['register.serial_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snap_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('face_direction', sa.Integer(), nullable=False),
    sa.Column('face_type', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('track_length', sa.Integer(), nullable=False),
    sa.Column('track_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snap_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snap_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['snap_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snap_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('face_score', sa.Float(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snap_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    op.drop_table('body')
    op.drop_table('basic')
    op.drop_table('snapshot')
    op.drop_table('register')
    # ### end Alembic commands ###
